# Generated by Django 3.1.6 on 2021-02-14 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210213_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Uunit', models.FloatField(choices=[(1.0, 'm/s'), (0.2777777777777778, 'km/hr')], max_length=3)),
                ('t', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Tunit', models.FloatField(choices=[(1.0, 's'), (60.0, 'min'), (3600.0, 'hr')], max_length=3)),
                ('a', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Aunit', models.FloatField(choices=[(1.0, 'm/s²'), (0.27777777777778, 'km/hr²')], max_length=3)),
            ],
        ),
    ]
