# Generated by Django 3.1.6 on 2021-02-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Qunit', models.FloatField(choices=[(1.0, 'C'), (1000.0, 'KC')], max_length=10)),
                ('t', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Tunit', models.FloatField(choices=[(0.001, 'ms'), (1.0, 's'), (60.0, 'min'), (3600.0, 'hr')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Question3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Uunit', models.FloatField(choices=[(1.0, 'm/s'), (0.2777777777777778, 'km/hr')], max_length=3)),
                ('a', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Aunit', models.FloatField(choices=[(1.0, 'm/s²'), (0.27777777777778, 'km/hr²')], max_length=3)),
                ('s', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Sunit', models.FloatField(choices=[(1.0, 'm'), (1000.0, 'km'), (0.01, 'cm')])),
            ],
        ),
    ]
