# Generated by Django 3.1.6 on 2021-02-14 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_question4'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Munit', models.FloatField(choices=[(1.0, 'kg'), (100.0, 'tonne'), (0.001, 'g')], max_length=7)),
                ('a', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Aunit', models.FloatField(choices=[(1.0, 'm/s²'), (0.27777777777778, 'km/hr²')], max_length=7)),
            ],
        ),
    ]
