# Generated by Django 3.1.6 on 2021-02-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_question7'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m', models.DecimalField(decimal_places=2, max_digits=5)),
                ('munit', models.FloatField(choices=[(1, 'g'), (1000, 'kg')], max_length=10)),
                ('v', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vunit', models.FloatField(choices=[(1, 'm/s'), (0.27777, 'km/h')], max_length=10)),
            ],
        ),
    ]
