# Generated by Django 3.1.6 on 2021-02-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_question8'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question9',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Munit', models.FloatField(choices=[(1.0, 'kg'), (100.0, 'tonne'), (0.001, 'g')], max_length=10)),
                ('h', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Hunit', models.FloatField(choices=[(1.0, 'm'), (1000.0, 'km'), (0.01, 'cm')], max_length=10)),
            ],
        ),
    ]
