# Generated by Django 3.1.6 on 2021-02-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_question9'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Funit', models.FloatField(choices=[(1.0, 'N'), (1000.0, 'kN')], max_length=10)),
                ('T', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Tunit', models.FloatField(choices=[(1.0, 's'), (60.0, 'min'), (3600.0, 'hr')], max_length=10)),
            ],
        ),
    ]
