# Generated by Django 3.1.6 on 2021-02-14 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_question10'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question10',
        ),
    ]
